export const ADD_PROJECT = 'ADD_PROJECT'
export const CHANGE_PROJECT = 'CHANGE_PROJECT'
export const DELETE_PROJECT = 'DELETE_PROJECT'
export const DEFINE_PROJECTS = 'DEFINE_PROJECTS'

export const NOTIFY = 'NOTIFY'

export const DEFINE_TASKS = 'DEFINE_TASKS'